let shopItemsData = [
  {
    "id": "abcd",
    "name": "Nitrile Gloves",
    "composition": "Nitrile, Paperboard",
    "unit": "1 pair",
    "co2kg": 0.084,
    "plastic": 8.8,
    "wood": 0,
    "paper": 1.3481,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 10.1481,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 58.66,
    "lcaUse": 0,
    "lcaTrnsp": 28.16,
    "lcaEol": 13.18,
    "lcaMfgKg": 0.0492744,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0236544,
    "lcaEolKg": 0.0110712,
    "notesTitle": "",
    "notes": "",
    "top": -10,
    "left": 20,
    "deg": 0.5,
    "img": "images/img-1.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "abce",
    "name": "Latex  Gloves",
    "composition": "Latex, Paperboard",
    "unit": "1 pair",
    "co2kg": 0.03,
    "plastic": 8.8,
    "wood": 0,
    "paper": 1.3481,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 10.1481,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 44.06,
    "lcaUse": 0,
    "lcaTrnsp": 55.94,
    "lcaEol": 0,
    "lcaMfgKg": 0.013218,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.016782,
    "lcaEolKg": 0,
    "notesTitle": "NOTES",
    "notes": "No EOL Data for Latex",
    "top": 8,
    "left": -10,
    "deg": -1,
    "img": "images/img-2.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "abdc",
    "name": "Facemask",
    "composition": "PP, Paperboard, Spandex & PET, Steel",
    "unit": "1 unit",
    "co2kg": 0.056,
    "plastic": 3.402,
    "wood": 0,
    "paper": 0.6924,
    "fabrictextile": 0.468,
    "glass": 0,
    "metal": 0.134,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 4.6964,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 63.28,
    "lcaUse": 0,
    "lcaTrnsp": 20.95,
    "lcaEol": 15.77,
    "lcaMfgKg": 0.0354368,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.011732,
    "lcaEolKg": 0.0088312,
    "notesTitle": "",
    "notes": "",
    "top": -7,
    "left": -5,
    "deg": 0.3,
    "img": "images/img-3.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "abde",
    "name": "Wash Cup PP",
    "composition": "PP, LDPE",
    "unit": "1 unit",
    "co2kg": 0.021,
    "plastic": 2.5283,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 2.5283,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 39.32,
    "lcaUse": 0,
    "lcaTrnsp": 29.96,
    "lcaEol": 30.72,
    "lcaMfgKg": 0.0082572,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0062916,
    "lcaEolKg": 0.0064512,
    "notesTitle": "",
    "notes": "",
    "top": 6,
    "left": 8,
    "deg": -0.6,
    "img": "images/img-4.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "abec",
    "name": "Wash Cup Eco",
    "composition": "PLA Corn",
    "unit": "1 unit",
    "co2kg": 0.046,
    "plastic": 5.0959,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 5.0959,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 51.94,
    "lcaUse": 0,
    "lcaTrnsp": 22.2,
    "lcaEol": 25.86,
    "lcaMfgKg": 0.0238924,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.010212,
    "lcaEolKg": 0.0118956,
    "notesTitle": "",
    "notes": "",
    "top": 2,
    "left": 12,
    "deg": 0.1,
    "img": "images/img-5.png",
    "bgCol": "var(--item-green)"
  },
  {
    "id": "abed",
    "name": "Green Soap",
    "composition": "Concentrate, HDPE, PP, PVC, PS",
    "unit": "15ml of concentrate",
    "co2kg": 0.048,
    "plastic": 1.3503,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 1.3503,
    "greywater": 90,
    "energyuseKwh": 0,
    "lcaMfg": 10.18,
    "lcaUse": 0,
    "lcaTrnsp": 81.48,
    "lcaEol": 8.34,
    "lcaMfgKg": 0.0048864,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0391104,
    "lcaEolKg": 0.0040032,
    "notesTitle": "NOTES",
    "notes": "Data Gap—No liquid Data",
    "top": -12,
    "left": -19,
    "deg": 0.8,
    "img": "images/img-6.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "acbe",
    "name": "Surface Disinfection",
    "composition": "Liquid, HDPE, PP, PVC, Steel, TPE-S, Adhesive",
    "unit": "30 ml",
    "co2kg": 0.086,
    "plastic": 2.3666,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0.665,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 3.0316,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 10.02,
    "lcaUse": 0,
    "lcaTrnsp": 82.34,
    "lcaEol": 7.64,
    "lcaMfgKg": 0.0086172,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0708124,
    "lcaEolKg": 0.0065704,
    "notesTitle": "NOTES",
    "notes": "No liquid Data.<br>Adhesive Data Missing—Data Gap!",
    "top": 4,
    "left": -3,
    "deg": 0.4,
    "img": "images/img-7.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "acbd",
    "name": "Safety Razor",
    "composition": "PP, Paperboard, Steel",
    "unit": "1 unit",
    "co2kg": 0.038,
    "plastic": 4.3,
    "wood": 0,
    "paper": 2.2121,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0.2,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 6.7121,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 66.4,
    "lcaUse": 0,
    "lcaTrnsp": 32.28,
    "lcaEol": 1.32,
    "lcaMfgKg": 0.025232,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0122664,
    "lcaEolKg": 0.0005016,
    "notesTitle": "",
    "notes": "",
    "top": 9,
    "left": 7,
    "deg": -0.2,
    "img": "images/img-8.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "acde",
    "name": "Skin Marker",
    "composition": "PP, INK, PE, PET",
    "unit": "1 reusable item",
    "co2kg": 0.073,
    "plastic": 7.498,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 1.5,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 7.498,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 43.8,
    "lcaUse": 0,
    "lcaTrnsp": 32.37,
    "lcaEol": 23.83,
    "lcaMfgKg": 0.031974,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0236301,
    "lcaEolKg": 0.0173959,
    "notesTitle": "",
    "notes": "",
    "top": 0,
    "left": 3,
    "deg": -0.8,
    "img": "images/img-9.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "acdb",
    "name": "Tattoo Cover—Polyurethane Wrap",
    "composition": "Paper, LDPE, PUR, PET, Adhesive",
    "unit": "1 sheet (15x18cm)",
    "co2kg": 0.041,
    "plastic": 3.12,
    "wood": 0,
    "paper": 3.2157,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 6.3361,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 45.31,
    "lcaUse": 0,
    "lcaTrnsp": 33.9,
    "lcaEol": 20.79,
    "lcaMfgKg": 0.0185771,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.013899,
    "lcaEolKg": 0.0085239,
    "notesTitle": "NOTES",
    "notes": "Adhesive Data Missing—Data Gap!",
    "top": 14,
    "left": -12,
    "deg": 0,
    "img": "images/img-10.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "aced",
    "name": "Paper Towel",
    "composition": "Paperboard, Paper, LDPE",
    "unit": "1 sheet",
    "co2kg": 0.007,
    "plastic": 0.0557,
    "wood": 0,
    "paper": 2.8937,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 2.9494,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 95.7,
    "lcaUse": 0,
    "lcaTrnsp": 0.72,
    "lcaEol": 3.58,
    "lcaMfgKg": 0.006699,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0000504,
    "lcaEolKg": 0.0002506,
    "notesTitle": "",
    "notes": "",
    "top": -16,
    "left": 17,
    "deg": 0.1,
    "img": "images/img-11.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "aceb",
    "name": "Rubbish bag",
    "composition": "LDPE, Paper, Adhesive",
    "unit": "1 bag",
    "co2kg": 0.031,
    "plastic": 6.95,
    "wood": 0,
    "paper": 0.0674,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0.0037,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 7.0211,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 45.12,
    "lcaUse": 0,
    "lcaTrnsp": 6.89,
    "lcaEol": 48,
    "lcaMfgKg": 0.0139872,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0021359,
    "lcaEolKg": 0.01488,
    "notesTitle": "",
    "notes": "",
    "top": -3,
    "left": 12,
    "deg": 0.4,
    "img": "images/img-12.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "adbc",
    "name": "Squeeze Bottle",
    "composition": "LDPE",
    "unit": "1 reusable item",
    "co2kg": 0.3,
    "plastic": 39.937,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 39.937,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 40.65,
    "lcaUse": 0,
    "lcaTrnsp": 26.46,
    "lcaEol": 32.89,
    "lcaMfgKg": 0.12195,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.07938,
    "lcaEolKg": 0.09867,
    "notesTitle": "",
    "notes": "",
    "top": 0,
    "left": -5,
    "deg": -0.6,
    "img": "images/img-13.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "adbe",
    "name": "Hand Sanitizer",
    "composition": "Liquid, HDPE, PP, PVC, Adhesive",
    "unit": "1 pump (2ml)",
    "co2kg": 0.018,
    "plastic": 0.1554,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0.0005,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0.1559,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 31.67,
    "lcaUse": 0,
    "lcaTrnsp": 42.82,
    "lcaEol": 25.51,
    "lcaMfgKg": 0.0057006,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0077076,
    "lcaEolKg": 0.0045918,
    "notesTitle": "NOTES",
    "notes": "Liquid Data not complete—Data Gap!",
    "top": 20,
    "left": 0,
    "deg": 0.9,
    "img": "images/img-14.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "adcb",
    "name": "Instrument Cleaner",
    "composition": "Concentrate, HDPE, PP, PVC, Adhesive",
    "unit": "15 ml",
    "co2kg": 0.024,
    "plastic": 1.1145,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0.0051,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 1.1196,
    "greywater": 15,
    "energyuseKwh": 0,
    "lcaMfg": 16.58,
    "lcaUse": 0,
    "lcaTrnsp": 69.83,
    "lcaEol": 13.59,
    "lcaMfgKg": 0.0039792,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0167592,
    "lcaEolKg": 0.0032616,
    "notesTitle": "NOTES",
    "notes": "Liquid Data not complete—Data Gap!",
    "top": -9,
    "left": -16,
    "deg": -0.1,
    "img": "images/img-15.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "adce",
    "name": "Stencil Paper",
    "composition": "Paperboard, Paper, LDPE, Adhesive",
    "unit": "1 sheet",
    "co2kg": 0.013,
    "plastic": 0.0049,
    "wood": 0,
    "paper": 2.34,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0.0002,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 2.3451,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 39.9,
    "lcaUse": 0,
    "lcaTrnsp": 59.93,
    "lcaEol": 0.17,
    "lcaMfgKg": 0.005187,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0077909,
    "lcaEolKg": 0.0000221,
    "notesTitle": "",
    "notes": "",
    "top": 2,
    "left": -11,
    "deg": -0.4,
    "img": "images/img-16.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "adeb",
    "name": "Stencil Ink",
    "composition": "Liquid, HDPE, PP, Paper",
    "unit": "1 print",
    "co2kg": 0.003,
    "plastic": 0.008,
    "wood": 0,
    "paper": 0.0001,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0.0081,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 15.32,
    "lcaUse": 0,
    "lcaTrnsp": 78.08,
    "lcaEol": 6.6,
    "lcaMfgKg": 0.0004596,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0023424,
    "lcaEolKg": 0.000198,
    "notesTitle": "NOTES",
    "notes": "No Adhesive Data for Label",
    "top": 9,
    "left": 10,
    "deg": 0.2,
    "img": "images/img-17.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "adec",
    "name": "Stencil transfer",
    "composition": "Liquid, PP, LDPE, PVC, Steel, PS, TPE-S",
    "unit": "1 application (0.4ml)",
    "co2kg": 0.003,
    "plastic": 0.0103,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0.0011,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0.0114,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 28.97,
    "lcaUse": 0,
    "lcaTrnsp": 65.99,
    "lcaEol": 5.04,
    "lcaMfgKg": 0.0008691,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0019797,
    "lcaEolKg": 0.0001512,
    "notesTitle": "NOTES",
    "notes": "Liquid Data not complete—Data Gap!<br>No Adhesive Data for Label",
    "top": 5,
    "left": 12,
    "deg": 0.7,
    "img": "images/img-18.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "aebd",
    "name": "Isopropyl Alocohol Swab",
    "composition": "Isopropyl, Paper, Paperboard, Viscose, PE, Aluminium",
    "unit": "1 swab",
    "co2kg": 0.278,
    "plastic": 0,
    "wood": 0,
    "paper": 0.2509,
    "fabrictextile": 0.1,
    "glass": 0,
    "metal": 0.0651,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0.5136,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 71.16,
    "lcaUse": 0,
    "lcaTrnsp": 28.28,
    "lcaEol": 0.56,
    "lcaMfgKg": 0.1978248,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0786184,
    "lcaEolKg": 0.0015568,
    "notesTitle": "NOTES",
    "notes": "EOL Data incomplete for Incineration calculation",
    "top": -15,
    "left": -5,
    "deg": 0.5,
    "img": "images/img-19.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "aebc",
    "name": "Microporous Tape",
    "composition": "Viscose, Paperboard, Adhesive",
    "unit": "1 unit",
    "co2kg": 0.000028,
    "plastic": 0,
    "wood": 0,
    "paper": 0.0028,
    "fabrictextile": 0.0282,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0.002,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0.033,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 65.58,
    "lcaUse": 0,
    "lcaTrnsp": 31.04,
    "lcaEol": 3.38,
    "lcaMfgKg": 0.0000183624,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0000086912,
    "lcaEolKg": 9.464e-7,
    "notesTitle": "NOTES",
    "notes": "Acrylic Adhesive Data Missing!",
    "top": 12,
    "left": 6,
    "deg": 1,
    "img": "images/img-20.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "aecd",
    "name": "Tongue Depressor",
    "composition": "Wood (Birch), Paper, Paperboard",
    "unit": "",
    "co2kg": 0.023,
    "plastic": 0,
    "wood": 2.1,
    "paper": 0.8739,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 2.9739,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 70.3,
    "lcaUse": 0,
    "lcaTrnsp": 29.53,
    "lcaEol": 0.17,
    "lcaMfgKg": 0.016169,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0067919,
    "lcaEolKg": 0.0000391,
    "notesTitle": "NOTES",
    "notes": "No Birch Wood Data—Data Gap!",
    "top": 4,
    "left": -17,
    "deg": -0.8,
    "img": "images/img-21.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "aecb",
    "name": "Workstation Cover Eco",
    "composition": "PLA Corn, Cardboard",
    "unit": "1 sheet",
    "co2kg": 0.073,
    "plastic": 27.1,
    "wood": 0,
    "paper": 1.1667,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 28.2667,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 54.11,
    "lcaUse": 0,
    "lcaTrnsp": 45.89,
    "lcaEol": 0,
    "lcaMfgKg": 0.0395003,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0334997,
    "lcaEolKg": 0,
    "notesTitle": "NOTES",
    "notes": "No EOL Data!",
    "top": -7,
    "left": -10,
    "deg": -0.5,
    "img": "images/img-22.png",
    "bgCol": "var(--item-green)"
  },
  {
    "id": "aedc",
    "name": "AAA Batteries",
    "composition": "Nickel plated steel container & chemicals, nickel coated steel, manganese dioxide and graphite rods, alkaline electrolyte, zinc gel, brass nail , zinc coated steel lid (positive pin, Anode), sperator (laminated paper) & plastic gasket.",
    "unit": "1 battery",
    "co2kg": 0.174,
    "plastic": 0,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 11.4,
    "solid": 11.4,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 95.59,
    "lcaUse": 0,
    "lcaTrnsp": 4.41,
    "lcaEol": 0,
    "lcaMfgKg": 0.1663266,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0076734,
    "lcaEolKg": 0,
    "notesTitle": "NOTES",
    "notes": "No EOL Data!",
    "top": -2,
    "left": 9,
    "deg": 0.2,
    "img": "images/img-23.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "aedb",
    "name": "Bottle Sleeve ECO",
    "composition": "PLA Corn, Cardboard",
    "unit": "1 unit",
    "co2kg": 0.009,
    "plastic": 1.8,
    "wood": 0,
    "paper": 0.1773,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 1.9773,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 54.05,
    "lcaUse": 0,
    "lcaTrnsp": 45.95,
    "lcaEol": 0,
    "lcaMfgKg": 0.0048645,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0041355,
    "lcaEolKg": 0,
    "notesTitle": "NOTES",
    "notes": "No EOL Data!",
    "top": -18,
    "left": -6,
    "deg": 0,
    "img": "images/img-24.png",
    "bgCol": "var(--item-green)"
  },
  {
    "id": "baec",
    "name": "Bottle Sleeve LDPE",
    "composition": "LDPE, Cardboard",
    "unit": "1 unit",
    "co2kg": 0.012,
    "plastic": 1.4,
    "wood": 0,
    "paper": 0.1411,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 1.5411,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 33.23,
    "lcaUse": 0,
    "lcaTrnsp": 32.9,
    "lcaEol": 33.87,
    "lcaMfgKg": 0.0039876,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.003948,
    "lcaEolKg": 0.0040644,
    "notesTitle": "",
    "notes": "",
    "top": 10,
    "left": 20,
    "deg": 0.6,
    "img": "images/img-25.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "baed",
    "name": "Distilled Water          Packaging",
    "composition": "HDPE, PP",
    "unit": "Reusable",
    "co2kg": 0.354,
    "plastic": 53.98,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 53.98,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 54.8,
    "lcaUse": 0,
    "lcaTrnsp": 0,
    "lcaEol": 45.2,
    "lcaMfgKg": 0.193992,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0,
    "lcaEolKg": 0.160008,
    "notesTitle": "NOTES",
    "notes": "No Transportation Data!",
    "top": 12,
    "left": 6,
    "deg": -1,
    "img": "images/img-26.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bace",
    "name": "Distilled Water Refill",
    "composition": "Distilled Water",
    "unit": "10 ml",
    "co2kg": 0.000013,
    "plastic": 0,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0,
    "greywater": 10,
    "energyuseKwh": 0,
    "lcaMfg": 100,
    "lcaUse": 0,
    "lcaTrnsp": 0,
    "lcaEol": 0,
    "lcaMfgKg": 0.000013,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0,
    "lcaEolKg": 0,
    "notesTitle": "NOTES",
    "notes": "No EOL Data!",
    "top": -17,
    "left": 6,
    "deg": 0.4,
    "img": "images/img-27.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bacd",
    "name": "SUP Cartidge Grip",
    "composition": "Nylon, TPE-S, Cardboard, PVC, Tyvek",
    "unit": "1 unit",
    "co2kg": 0.64,
    "plastic": 38.7,
    "wood": 0,
    "paper": 7.8,
    "fabrictextile": 0.6,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 47.1,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 53.75,
    "lcaUse": 0,
    "lcaTrnsp": 30,
    "lcaEol": 16.25,
    "lcaMfgKg": 0.344,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.192,
    "lcaEolKg": 0.104,
    "notesTitle": "",
    "notes": "",
    "top": -2,
    "left": -16,
    "deg": -0.3,
    "img": "images/img-28.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bade",
    "name": "Drive Pins",
    "composition": "Steel (SAE316), LDPE, Aluminium (?),Paper",
    "unit": "5 reusable units",
    "co2kg": 0.14,
    "plastic": 1.19,
    "wood": 0,
    "paper": 0.265,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 3.46,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 1.144,
    "greywater": 200,
    "energyuseKwh": 0,
    "lcaMfg": 73.8,
    "lcaUse": 11.25,
    "lcaTrnsp": 12.44,
    "lcaEol": 2.51,
    "lcaMfgKg": 0.10332,
    "lcaUseKg": 0.01575,
    "lcaTrnspKg": 0.017416,
    "lcaEolKg": 0.003514,
    "notesTitle": "NOTES",
    "notes": "EOL Data Gap!",
    "top": 0,
    "left": 11,
    "deg": 0.1,
    "img": "images/img-29.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "badc",
    "name": "HHP III adapter",
    "composition": "Brass (MS58), Steel (SAE316)",
    "unit": "1 reusable unit",
    "co2kg": 0.25,
    "plastic": 0,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 28.847,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0,
    "greywater": 200,
    "energyuseKwh": 0,
    "lcaMfg": 93.47,
    "lcaUse": 6.53,
    "lcaTrnsp": 0,
    "lcaEol": 0,
    "lcaMfgKg": 0.233675,
    "lcaUseKg": 0.016325,
    "lcaTrnspKg": 0,
    "lcaEolKg": 0,
    "notesTitle": "NOTES",
    "notes": "Transportation Data Missing!",
    "top": 8,
    "left": 0,
    "deg": 0.4,
    "img": "images/img-30.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bced",
    "name": "Ekata",
    "composition": "Brass (MS58), Aluminium (AlZnMgCu), Steel (SAE316)",
    "unit": "1 use incl. production",
    "co2kg": 1.43,
    "plastic": 0,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 102.78,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0,
    "greywater": 200,
    "energyuseKwh": 0,
    "lcaMfg": 98.88,
    "lcaUse": 1.12,
    "lcaTrnsp": 0,
    "lcaEol": 0,
    "lcaMfgKg": 1.413984,
    "lcaUseKg": 0.016016,
    "lcaTrnspKg": 0,
    "lcaEolKg": 0,
    "notesTitle": "NOTES",
    "notes": "Production & single Disinfection!",
    "top": 11,
    "left": -14,
    "deg": 1,
    "img": "images/img-31.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bcea",
    "name": "Tool Sterilization",
    "composition": "Distilled Water, Ultrasonic Cleaner",
    "unit": "1 cycle",
    "co2kg": 0.016,
    "plastic": 0,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0,
    "greywater": 300,
    "energyuseKwh": 0.0275,
    "lcaMfg": 0,
    "lcaUse": 100,
    "lcaTrnsp": 0,
    "lcaEol": 0,
    "lcaMfgKg": 0,
    "lcaUseKg": 0.016,
    "lcaTrnspKg": 0,
    "lcaEolKg": 0,
    "notesTitle": "NOTES",
    "notes": "LCA EOL Data Gap!",
    "top": 20,
    "left": -8,
    "deg": -0.7,
    "img": "images/img-32.png",
    "bgCol": "var(--item-yellow)"
  },
  {
    "id": "bcad",
    "name": "Ink Cap PP",
    "composition": "PP, LDPE",
    "unit": "1 unit",
    "co2kg": 0.005,
    "plastic": 0.6381,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0.6381,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 38.72,
    "lcaUse": 0,
    "lcaTrnsp": 30.64,
    "lcaEol": 30.64,
    "lcaMfgKg": 0.001936,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.001532,
    "lcaEolKg": 0.001532,
    "notesTitle": "",
    "notes": "",
    "top": 17,
    "left": 0,
    "deg": -0.3,
    "img": "images/img-33.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bcae",
    "name": "Ink Cap ECO",
    "composition": "Paper, Steel",
    "unit": "1 unit",
    "co2kg": 0.003,
    "plastic": 0,
    "wood": 0,
    "paper": 0.5637,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0.0035,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0.5707,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 57.07,
    "lcaUse": 0,
    "lcaTrnsp": 42.37,
    "lcaEol": 0.56,
    "lcaMfgKg": 0.0017121,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0012711,
    "lcaEolKg": 0.0000168,
    "notesTitle": "",
    "notes": "",
    "top": -18,
    "left": -5,
    "deg": 0,
    "img": "images/img-34.png",
    "bgCol": "var(--item-green)"
  },
  {
    "id": "bcda",
    "name": "Tattoo Ink",
    "composition": "INK, PET, Glass, PS, PVC",
    "unit": "1 ink cap (2.3ml)",
    "co2kg": 0.038,
    "plastic": 0.49,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0.138,
    "metal": 0,
    "ink": 2.3,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0.628,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 15.03,
    "lcaUse": 0,
    "lcaTrnsp": 82.83,
    "lcaEol": 2.14,
    "lcaMfgKg": 0.0057114,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0314754,
    "lcaEolKg": 0.0008132,
    "notesTitle": "",
    "notes": "",
    "top": 8,
    "left": 15,
    "deg": 0.6,
    "img": "images/img-35.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bcde",
    "name": "Cartridge Tray PP",
    "composition": "PP, Cardboard",
    "unit": "1 unit",
    "co2kg": 0.058,
    "plastic": 6.3,
    "wood": 0,
    "paper": 2.28,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 8.58,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 37.68,
    "lcaUse": 0,
    "lcaTrnsp": 34.95,
    "lcaEol": 27.37,
    "lcaMfgKg": 0.0218544,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.020271,
    "lcaEolKg": 0.0158746,
    "notesTitle": "",
    "notes": "",
    "top": 0,
    "left": 20,
    "deg": 0.4,
    "img": "images/img-36.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bdea",
    "name": "Cartridge Tray Eco",
    "composition": "Paper, Cardboard",
    "unit": "1 unit",
    "co2kg": 0.045,
    "plastic": 0,
    "wood": 0,
    "paper": 13.38,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 13.38,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 38.62,
    "lcaUse": 0,
    "lcaTrnsp": 60.64,
    "lcaEol": 0.74,
    "lcaMfgKg": 0.017379,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.027288,
    "lcaEolKg": 0.000333,
    "notesTitle": "",
    "notes": "",
    "top": -2,
    "left": 6,
    "deg": -0.2,
    "img": "images/img-37.png",
    "bgCol": "var(--item-green)"
  },
  {
    "id": "bdec",
    "name": "Cartridge Needle 3RL",
    "composition": "Paperboard, PP, PVC, Tyvek, TPE-S, Steel SAe316, Solder, Epoxy",
    "unit": "1 unit",
    "co2kg": 0.067,
    "plastic": 4.255,
    "wood": 0,
    "paper": 1.9434,
    "fabrictextile": 0.197,
    "glass": 0,
    "metal": 0.07,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0.007,
    "composite": 0,
    "solid": 6.4724,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 61.14,
    "lcaUse": 0,
    "lcaTrnsp": 22.72,
    "lcaEol": 16.14,
    "lcaMfgKg": 0.0409638,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0152224,
    "lcaEolKg": 0.0108138,
    "notesTitle": "",
    "notes": "",
    "top": 13,
    "left": 10,
    "deg": 0.8,
    "img": "images/img-38.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bdae",
    "name": "Floor Disinfection",
    "composition": "Concentrate, PP, Paper, PS, Adhesive",
    "unit": "1 cleaning (15ml)",
    "co2kg": 0.041,
    "plastic": 1.4013,
    "wood": 0,
    "paper": 0.0428,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0.008,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 1.4521,
    "greywater": 15,
    "energyuseKwh": 0,
    "lcaMfg": 12.81,
    "lcaUse": 0,
    "lcaTrnsp": 78.46,
    "lcaEol": 8.73,
    "lcaMfgKg": 0.0052521,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0321686,
    "lcaEolKg": 0.0035793,
    "notesTitle": "",
    "notes": "",
    "top": 6,
    "left": -7,
    "deg": -0.4,
    "img": "images/img-39.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bdac",
    "name": "After Care",
    "composition": "Cream, PET, Adhesive, PS, PVC",
    "unit": "1 gm",
    "co2kg": 0.006,
    "plastic": 6.094,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0.0033,
    "cream": 0.6,
    "epoxy": 0,
    "composite": 0,
    "solid": 1.2127,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 30.65,
    "lcaUse": 0,
    "lcaTrnsp": 68.12,
    "lcaEol": 1.23,
    "lcaMfgKg": 0.001839,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.0040872,
    "lcaEolKg": 0.0000738,
    "notesTitle": "",
    "notes": "",
    "top": 10,
    "left": -16,
    "deg": -0.7,
    "img": "images/img-40.png",
    "bgCol": "var(--item-pink)"
  },
  {
    "id": "bdce",
    "name": "Sharps Container",
    "composition": "PP",
    "unit": "1 cartridge needle disposed",
    "co2kg": 0.00074,
    "plastic": 0.872,
    "wood": 0,
    "paper": 0,
    "fabrictextile": 0,
    "glass": 0,
    "metal": 0,
    "ink": 0,
    "adhesive": 0,
    "cream": 0,
    "epoxy": 0,
    "composite": 0,
    "solid": 0.872,
    "greywater": 0,
    "energyuseKwh": 0,
    "lcaMfg": 43.46,
    "lcaUse": 0,
    "lcaTrnsp": 26.61,
    "lcaEol": 29.93,
    "lcaMfgKg": 0.000321604,
    "lcaUseKg": 0,
    "lcaTrnspKg": 0.000196914,
    "lcaEolKg": 0.000221482,
    "notesTitle": "",
    "notes": "",
    "top": -19,
    "left": 2,
    "deg": 0,
    "img": "images/img-41.png",
    "bgCol": "var(--item-pink)"
  }
]